/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appbanco;

import com.formdev.flatlaf.FlatLightLaf;
import javax.swing.UIManager;



/**
 *
 * @author guiaw
 */
public class Terminal extends javax.swing.JFrame {
    Conta conta1, conta2;

    /**
     * Creates new form Terminal
     */
    public Terminal() {
        initComponents();
        conta1 = new Conta("Joao", 10, 200, 2000);
        conta2 = new Conta("Pedro", 11, 300, 3000);
        
        imprimirConta();
        imprimirConta2();
    }
    
    public void imprimirConta(){
        lblnomeConta.setText(conta1.getNome());
        double num = conta1.getSaldo();
        String con = Double.toString(num);
        lblsaldoAtual.setText(con);
    
    }
    public void imprimirConta2(){
        lblnomeconta2.setText(conta2.getNome());
        double num = conta2.getSaldo();
        String con = Double.toString(num);
        lblsaldovalor2.setText(con);
    
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblconta1 = new javax.swing.JLabel();
        btnsacar = new javax.swing.JButton();
        txtvalor = new javax.swing.JTextField();
        lblnomeConta = new javax.swing.JLabel();
        lblsaldo = new javax.swing.JLabel();
        lblsaldoAtual = new javax.swing.JLabel();
        bntdepositar = new javax.swing.JButton();
        lblconta2 = new javax.swing.JLabel();
        lblnomeconta2 = new javax.swing.JLabel();
        lblsaldo2 = new javax.swing.JLabel();
        lblsaldovalor2 = new javax.swing.JLabel();
        txtvalor2 = new javax.swing.JTextField();
        bntsacar2 = new javax.swing.JButton();
        btndepositar2 = new javax.swing.JButton();
        btntransferencia12 = new javax.swing.JButton();
        btntransferencia21 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblconta1.setText("Conta 1:");

        btnsacar.setText("sacar");
        btnsacar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsacarActionPerformed(evt);
            }
        });

        txtvalor.setText("valor");

        lblnomeConta.setText("Nome");

        lblsaldo.setText("Saldo");

        lblsaldoAtual.setText("...");

        bntdepositar.setText("Depositar");
        bntdepositar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntdepositarActionPerformed(evt);
            }
        });

        lblconta2.setText("Conta 2:");

        lblnomeconta2.setText("Nome");

        lblsaldo2.setText("Saldo");

        lblsaldovalor2.setText("....");

        txtvalor2.setText("valor");

        bntsacar2.setText("Sacar");
        bntsacar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntsacar2ActionPerformed(evt);
            }
        });

        btndepositar2.setText("Depositar");
        btndepositar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndepositar2ActionPerformed(evt);
            }
        });

        btntransferencia12.setText("Transferir pra conta 2");
        btntransferencia12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntransferencia12ActionPerformed(evt);
            }
        });

        btntransferencia21.setText("Transferir pra conta1");
        btntransferencia21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntransferencia21ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblsaldo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblconta1, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblnomeConta, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                            .addComponent(lblsaldoAtual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblconta2, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                            .addComponent(lblsaldo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblnomeconta2, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                            .addComponent(lblsaldovalor2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnsacar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bntdepositar, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtvalor))
                            .addComponent(btntransferencia12))
                        .addGap(71, 71, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btndepositar2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtvalor2, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(bntsacar2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(btntransferencia21))
                        .addGap(47, 47, 47)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblnomeConta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblconta2)
                        .addComponent(lblnomeconta2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblconta1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblsaldovalor2, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(lblsaldo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblsaldoAtual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblsaldo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtvalor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtvalor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsacar)
                    .addComponent(bntsacar2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntdepositar)
                    .addComponent(btndepositar2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btntransferencia12)
                    .addComponent(btntransferencia21))
                .addContainerGap(95, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsacarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsacarActionPerformed
       try{
        double valor = Double.parseDouble(txtvalor.getText());
        conta1.sacar(valor);
       }catch(NumberFormatException ex){
           System.err.println(ex.getMessage());
       }
        imprimirConta();
    }//GEN-LAST:event_btnsacarActionPerformed

    private void bntdepositarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntdepositarActionPerformed
       double valor = Double.parseDouble(txtvalor.getText());
       conta1.deposito(valor);
       
       imprimirConta();
    }//GEN-LAST:event_bntdepositarActionPerformed

    private void bntsacar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntsacar2ActionPerformed
        double valor = Double.parseDouble(txtvalor2.getText());
        conta2.sacar(valor);
        
        imprimirConta2();
    }//GEN-LAST:event_bntsacar2ActionPerformed

    private void btndepositar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndepositar2ActionPerformed
       double valor = Double.parseDouble(txtvalor2.getText());
       conta2.deposito(valor);
       
       imprimirConta2();
    }//GEN-LAST:event_btndepositar2ActionPerformed

    private void btntransferencia12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntransferencia12ActionPerformed
        double valor = Double.parseDouble(txtvalor.getText());
        conta1.transferencia(conta2, valor);
        
        imprimirConta2();
        imprimirConta();
      
    }//GEN-LAST:event_btntransferencia12ActionPerformed

    private void btntransferencia21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntransferencia21ActionPerformed
        double valor = Double.parseDouble(txtvalor.getText());
        conta2.transferencia(conta1, valor);
        
        imprimirConta2();
        imprimirConta();
    }//GEN-LAST:event_btntransferencia21ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Terminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Terminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Terminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Terminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        try {
             UIManager.setLookAndFeel( new FlatLightLaf() );
             } catch( Exception ex ) {
             System.err.println( "Failed to initialize LaF" );
            }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Terminal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntdepositar;
    private javax.swing.JButton bntsacar2;
    private javax.swing.JButton btndepositar2;
    private javax.swing.JButton btnsacar;
    private javax.swing.JButton btntransferencia12;
    private javax.swing.JButton btntransferencia21;
    private javax.swing.JLabel lblconta1;
    private javax.swing.JLabel lblconta2;
    private javax.swing.JLabel lblnomeConta;
    private javax.swing.JLabel lblnomeconta2;
    private javax.swing.JLabel lblsaldo;
    private javax.swing.JLabel lblsaldo2;
    private javax.swing.JLabel lblsaldoAtual;
    private javax.swing.JLabel lblsaldovalor2;
    private javax.swing.JTextField txtvalor;
    private javax.swing.JTextField txtvalor2;
    // End of variables declaration//GEN-END:variables
}
